// <auto-generated />
using System;
using DailyOperations.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DailyOperations.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230708175001_adding powerType to Officers Table")]
    partial class addingpowerTypetoOfficersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DailyOperations.Domain.Entities.Members.AssistantsMilitaryDegree", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AssistantMilitaryDegrees");
                });

            modelBuilder.Entity("DailyOperations.Domain.Entities.Members.OfficerMilitaryDegree", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OfficerMilitaryDegrees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Degree = "ملازم",
                            DisplayOrder = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2L,
                            Degree = "ملازم أول",
                            DisplayOrder = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3L,
                            Degree = "نقيب",
                            DisplayOrder = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4L,
                            Degree = "رائد",
                            DisplayOrder = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5L,
                            Degree = "مقدم",
                            DisplayOrder = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6L,
                            Degree = "عقيد",
                            DisplayOrder = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7L,
                            Degree = "عميد",
                            DisplayOrder = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8L,
                            Degree = "لواء",
                            DisplayOrder = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9L,
                            Degree = "مساعد وزير",
                            DisplayOrder = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10L,
                            Degree = "مساعد أول وزير",
                            DisplayOrder = 8,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("DailyOperations.Domain.Entities.Members.PoliceAssistant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("AssistantsMilitaryDegreeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssistantsMilitaryDegreeId");

                    b.ToTable("PoliceAssistants");
                });

            modelBuilder.Entity("DailyOperations.Domain.Entities.Members.PoliceOfficer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("OfficerMilitaryDegreeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PowerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OfficerMilitaryDegreeId");

                    b.ToTable("PoliceOfficers");
                });

            modelBuilder.Entity("DailyOperations.Domain.Entities.Members.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleLetters")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("VehicleNumbers")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("DailyOperations.Domain.Entities.Soldier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Soldiers");
                });

            modelBuilder.Entity("DailyOperations.Domain.Entities.Members.PoliceAssistant", b =>
                {
                    b.HasOne("DailyOperations.Domain.Entities.Members.AssistantsMilitaryDegree", "AssistantsMilitaryDegree")
                        .WithMany()
                        .HasForeignKey("AssistantsMilitaryDegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssistantsMilitaryDegree");
                });

            modelBuilder.Entity("DailyOperations.Domain.Entities.Members.PoliceOfficer", b =>
                {
                    b.HasOne("DailyOperations.Domain.Entities.Members.OfficerMilitaryDegree", "OfficerMilitaryDegree")
                        .WithMany()
                        .HasForeignKey("OfficerMilitaryDegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficerMilitaryDegree");
                });
#pragma warning restore 612, 618
        }
    }
}
